<h1 style="text-align: center;"><b>Modern Topics in Interest Rate Modelling</b></h1>

### Roland Grinis

In [18]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt
plt.style.use("dark_background")
%matplotlib inline

## 1. Risk Free Rates (RFRs)

### 1.1 Extended $T$-forward measure

Short (risk-free, OIS) rate $r_t$ gives rise to bank account numeraire:

$$
dB_t = r_t B_t dt, \quad B_t = \exp \left( \int_0^t r_u du \right)
$$

The associcated risk neutral measure $Q$ is called the money-savings measure
Investing in the bank account after maturity, we obtain the extended zero-coupon: 
$$
P_{t,T} = 
\begin{cases}
  \mathbb{E}^Q_t \left[ \exp \left(- \int_{t,T} r_u du \right) \right] , & t\leq T\\
  \exp \left(- \int_{t,T} r_u du \right) = \frac{B_t}{B_T},            & t > T
\end{cases}
$$

The associated risk-neutral measure, denoted $Q^T$, corresponds to the $T$-forward measure for $t \leq T$
and the money-savings measure $Q$ after maturity.

### 1.2 Backward-looking forward rates

Forward Rate Agreement (FRA) contract has present value:

$$
PV_t = B_t \cdot \mathbb{E}^Q_{t} \left[ \tau \frac{\mathcal{P}_{T-\tau, T} - K}{B_T}  \right]
$$

with forward looking payoff:

$$
\mathcal{P}_{T-\tau, T} \equiv \mathcal{P}_{T-\tau, T} \left[ T' \rightarrow P_{T-\tau, T'} \right]
$$

or backward looking payoff:
$$
\mathcal{P}_{T-\tau, T} \equiv \mathcal{P}_{T-\tau, T} \left[ r_d \in \mathcal{B}(T - \tau, T) \right]
$$
where $\mathcal{B}(T - \tau, T)$ runs over business days in $\left[ T - \tau, T \right)$.

For example, the simple daily-compounded setting-in-arrears rates read:
$$
R_T \coloneqq R(T-\tau, T) = \mathcal{P}_{T-\tau, T} = \frac{1}{\delta} \left( \prod_{t \leq t_n < t+\delta} \left(1 + \delta_n r_{t_n} \right) - 1 \right)
$$

Or the daily arithmetic average setting-in-arrears rates read:

$$
A(T - \tau, T) = \mathcal{P}_{T-\tau, T} = \frac{1}{\delta} \sum_{t \leq t_n < t+\delta} \delta_n r_{t_n} 
$$

Passing to continous modelling:
$$
\frac{1}{\tau} \left[ \exp \left( \int_{T - \tau}^T r_u du \right)  - 1\right], \quad A(T - \tau, T)\approx \frac{1}{\tau} \int_{T - \tau}^T r_u du 
$$

and we get the relation:
$$
A(T - \tau, T) \approx \frac{1}{\tau} \log \left(1 + \tau R(T - \tau, T)\right)
$$



Passing to the extended $T$-forward measure, we obtain the compound forward rate as:
$$
R_{t,T} \coloneqq R_t(T - \tau, T) = \mathbb{E}^{Q^T}_{t} \left[  R(T - \tau, T) \right]
$$

which make $PV_t = 0$. We can evaluate the expectation:


* for $t \leq T-\tau$, $ R_{t,T} = \frac{1}{\tau} \left( \frac{P_{t, T - \tau}}{P_{t,T}} - 1\right)$ is analogous to IBOR forward rates.
* for $ T-\tau < t \leq T$, $ R_{t,T} = \frac{1}{\tau} \left( \frac{B_t}{B_{T - \tau} P_{t,T}} - 1\right)$ is daily compounding.
* post maturity $ R_{t,T} \equiv \frac{1}{\tau} \left( \frac{B_{T}}{B_{T - \tau}}  - 1\right)$ is known and fixed.

  
The yield curve $T \rightarrow P_{t,T}$ can be boostrapped from $T \rightarrow  R_{t,T}$ quotes.

The arithmetic average forward rate can be expressed as:
$$
A_{t,T} \coloneqq  A_t(T - \tau, T) = \mathbb{E}^{Q^T}_{t} \left[ \frac{1}{\tau} \log \left(1 + \tau R(T - \tau, T)\right) \right]
$$
and since the payoff is non-linear, $A_{t,T}$ is model dependent. A convexity correction can appear compared to market quotes:
$$
A_{t,T} = \frac{1}{\tau} \log \left(1 + \tau R_{t,T}\right) + \text{Convexity Correction}
$$

Interest Rate Swap (IRS) based on simple daily-compounding backward rates values:
$$
PV_t = \sum_{i=1}^n \tau_i P_{t,T_i}R_t(T_{i-1}, T_i) - K \cdot  \sum_{j=1}^m \tau'_i P_{t, T'_j}
$$
with floating leg tenors $T_0, \dots, T_n$ and fixed leg $T'_0, \dots, T'_m$ tenors. 

For $t < T_0$ forward swap rate with associated present value of a basis point evaluates:
$$
S_t(T_0, T_n) = \frac{P_{t,T_0} - P_{t,T_n}}{\text{PVBP}(t)} , \quad \text{PVBP}(t) = \sum_{j=1}^m \tau'_i P_{t, T'_j}
$$

The yield curve $T \rightarrow P_{t,T}$ can also get boostrapped from IRS quotes.

### 1.3 Forward Market Model (FMM)
As we approach maturity $T$, backward-looking rates settle to constant, and we need to choose a cutoff function to dampen volatility. 
  
A typical example is the linear cutoff $g_{t,T} = (T-t)^+ / \tau $ for $t \in (T-\tau, T)$ with $g_{t,T} \equiv 1$ for $t \leq T-\tau$ and $g_{t,T} \equiv 0$, $t \geq T$.  
  
In extended $T$-forward measure:
$$
dR_{t,T} = g_{t,T} \sigma_{t,T} (R_{t,T}) dW_t^{Q^T} \quad \text{martingale,}
$$

where $\sigma_{t,T} \equiv \sigma^T$ (Bachelier), or $\sigma_{t,T} \equiv \sigma^T R_{t,T}$ (Black), or  $\sigma_{t,T} \equiv \sigma^T (R_{t,T})^{\beta}$ (CEV), or Dupire local vol, or stochastic vol etc. with (multi-dimensional) Brownian motion $W_{t,T}$

In money-savings numeraire $B_t$, we get the drift:
$$
dR_{t,T} = g_{t,T} \sigma_{t,T}(R_{t,T}) \left[
\sum_{T' < T}\rho_{T',T} \frac{\tau' g_{t,T'} \sigma_{t,T'}(R_{t,T'})}{1 + \tau' R_{t,T'} } dt + dW_t^Q
\right]
$$
where the sum runs over shorter tenors and $\rho$ holds the correlation structure of the curve.

#### 1.3.1 Caplet Pricing

Using $P_{t,T}$ as numeraire, for simply-compound rates:

$$
V^{\text{Caplet}}_t \left[ R_{t,T}, K \right] = P_{t,T} \mathbb{E}_{t}^{Q^T} \left[ \tau \left( R(T-\tau, T) - K \right)^+ \right] 
$$

For arithmetic average compound rates, the choice of cutoff $g_{t,T}$ influence directly the convexity correction. 
One should attempt to choose it such that we have:
$$
V^{\text{Caplet}}_t \left[ A_{t,T}, K \right] = P_{t,T} \mathbb{E}_{t}^{Q^T} \left[ \tau \left( A(T-\tau, T) - K \right)^+ \right] =  P_{t,T} \mathbb{E}_{t}^{Q^T} \left[  \left( \log \left(1 + \tau R(T - \tau, T)\right)  - \tau K \right)^+ \right] 
$$ 

As reference, using the linear cutoff:
$$
\hat{g}_{t,T}^2 \coloneqq \int_{t,T} g_{t,T}^2(s)ds = 
\begin{cases}
  T - \frac{2}{3}\tau - t,  & t\leq T-\tau \\
  \frac{(T-t)^3}{3\tau^2},  & t > T - \tau
\end{cases}
$$

Bachelier model:
$$
dR_{t,T} = g_{t,T} \sigma dW_t^{Q^T}, \quad R(T-\tau, T) \sim \mathcal{N}\left(R_{t,T}, (\sigma\hat{g}_{t,T})^2 \right) 
$$

Black model:
$$
dR_{t,T} = g_{t,T} R_{t,T} \sigma dW_t^{Q^T}, \quad R(T-\tau, T) = R_{t,T} \exp \left( - \frac{(\sigma\hat{g}_{t,T})^2 }{2} + \mathcal{N}\left(0, (\sigma\hat{g}_{t,T})^2 \right)  \right)
$$

Market makers formula convention for arithmetic-average compound rates:
$$
V^{\text{Caplet}}_t \left[ A'_{t,T}, K \right] = \tau P_{t,T}\left[ \left( A'_{t,T} - K\right) \Phi\left(\frac{A'_{t,T} - K}{\sigma \hat{g}_{t,T} }\right) - \sigma \hat{g}_{t,T} \phi\left(\frac{A'_{t,T} - K}{\sigma \hat{g}_{t,T} }\right)\right]
$$
which is the Bachelier model (normal volatility, $\Phi$ and $\phi$ are normal distribution CDF and PDF respectively), or:
$$
V^{\text{Caplet}}_t \left[ A'_{t,T}, K \right] = \tau P_{t,T}\left[ A'_{t,T} \Phi\left(d_{+}\right) - K \Phi \left(d_{-} \right) \right], \quad d_{\pm} = \frac{\log (A'_{t,T} / K) \pm (\sigma \hat{g}_{t,T})^2 / 2 }{\sigma\hat{g}_{t,T}}
$$
with the Black model (log-normal volatility). No convexity correction is taken into account. However, the discounting $P_{t,T}$ is done with respect to the OIS curve, even if  $A'_{t,T}$ correspond to a different RFR rate (e.g. a Key Rate).

In [69]:
fwd_ruonia = pd.read_csv('data/forward_ruonia.csv')
fwd_key_rate = pd.read_csv('data/forward_cbr_key_rate.csv')
vol_key_rate = pd.read_csv('data/volatility_cbr_key_rate.csv')

In [70]:
fwd_ruonia

    forward_rate  time_to_maturity      tenor
0         0.2027          0.002740   0.002740
1         0.2071          0.019178   0.019178
2         0.2075          0.038356   0.038356
3         0.2081          0.083333   0.083333
4         0.2087          0.166667   0.166667
5         0.2111          0.250000   0.250000
6         0.2127          0.500000   0.500000
7         0.2059          0.750000   0.750000
8         0.2004          1.000000   1.000000
9         0.1853          2.000000   2.000000
10        0.1794          3.000000   3.000000
11        0.1760          4.000000   4.000000
12        0.1740          5.000000   5.000000
13        0.1726          6.000000   6.000000
14        0.1714          7.000000   7.000000
15        0.1706          8.000000   8.000000
16        0.1699          9.000000   9.000000
17        0.1694         10.000000  10.000000

In [71]:
fwd_key_rate

    forward_rate  time_to_maturity     tenor
0         0.2100           0.00274   0.00274
1         0.2112           0.25000   0.25000
2         0.2133           0.50000   0.50000
3         0.2067           0.75000   0.75000
4         0.2016           1.00000   1.00000
5         0.1852           2.00000   2.00000
6         0.1793           3.00000   3.00000
7         0.1761           4.00000   4.00000
8         0.1740           5.00000   5.00000
9         0.1726           6.00000   6.00000
10        0.1714           7.00000   7.00000
11        0.1706           8.00000   8.00000
12        0.1699           9.00000   9.00000
13        0.1694          10.00000  10.00000

In [78]:
vol_key_rate[vol_key_rate.tenor == 0.5]

     tenor  time_to_maturity  strike  implied_normal_vol
99     0.5               0.5   0.080            0.033399
100    0.5               0.5   0.090            0.031028
101    0.5               0.5   0.100            0.028903
102    0.5               0.5   0.110            0.027083
103    0.5               0.5   0.115            0.026308
104    0.5               0.5   0.120            0.025634
105    0.5               0.5   0.125            0.025071
106    0.5               0.5   0.130            0.024626
107    0.5               0.5   0.135            0.024305
108    0.5               0.5   0.140            0.024115
109    0.5               0.5   0.145            0.024057
110    0.5               0.5   0.150            0.024134
111    0.5               0.5   0.155            0.024345
112    0.5               0.5   0.160            0.024685
113    0.5               0.5   0.165            0.025151
114    0.5               0.5   0.170            0.025736
115    0.5               0.5   0.175            0.026431
116    0.5               0.5   0.180            0.027229
117    0.5               0.5   0.185            0.028122
118    0.5               0.5   0.190            0.029100
119    0.5               0.5   0.195            0.030156
120    0.5               0.5   0.200            0.031282
121    0.5               0.5   0.205            0.032471
122    0.5               0.5   0.210            0.033716
123    0.5               0.5   0.215            0.035011
124    0.5               0.5   0.220            0.036345
125    0.5               0.5   0.230            0.039059
126    0.5               0.5   0.240            0.041756
127    0.5               0.5   0.250            0.044395
128    0.5               0.5   0.275            0.050708
129    0.5               0.5   0.300            0.056682
130    0.5               0.5   0.325            0.062409
131    0.5               0.5   0.350            0.067959

### 1.4 Short Rate Models: Hull-White

Dynamics in money-savings risk-neutral measure $Q$ are given by:
$$
dr_t = \left( \theta_t - \lambda r_t \right) dt + \sigma dW_t
$$

with $\theta_t$ fixed by the HJM no-arbitrage condition. This can be rewritten as affine process:

$$
r_t = \alpha_t + x_t 
$$

where the deterministic part follows the HJM condition:
$$
\alpha_T = - \frac{\partial}{ \partial T}\log P_{t,T}  + \frac{\sigma^2}{2 \lambda^2} \left( 1- e^{\lambda (T-t)} \right)
$$
and the stochastic part:
$$
dx_t = - \lambda x_t dt + \sigma dW_t
$$
which is simply a Gaussian:
$$
x_T \sim \mathcal{N} \left( x_t e^{-\lambda(T-t)}, \quad \frac{\sigma^2}{2 \lambda} \left( 1- e^{-2\lambda (T-t)} \right) \right)
$$

Changing to the $T$-forward measure $Q^T$: 
$$
dx_t = - \left( \frac{\sigma^2}{\lambda} \left(1 - e^{-\lambda(T-t)} \right) + \lambda x_t \right) dt + \sigma dW^T_t
$$

which is also a gaussian with mean:
$$
\mathbb{E}^{Q^T}_{t} \left[ x_{t+\Delta} \right] = x_t e^{-\lambda \Delta} - \frac{\sigma^2}{\lambda^2} \left(1 - e^{-\lambda \Delta} \right) - \frac{\sigma^2}{2\lambda^2} \left(e^{-\lambda(T-t-\Delta)} - e^{-\lambda(T-t+\Delta)} \right) 
$$
and variance $\frac{\sigma^2}{2 \lambda} \left( 1- e^{-2\lambda \Delta} \right)$ as in measure $Q$.

#### 1.4.1 The Hull-White-Heston model

To price the volatility smile we rely on stochastic volatility models such as the Heston Model, which combined with Hull-White looks like:

$$
\left\{
\begin{array}{l}
    dx_t = - \lambda x_t dt + \sqrt{v_t} \text{d}W_t^x,  \\
    dv_t =  \kappa (\theta - v_t)\text{d}t + \varepsilon \sqrt{v_t} \text{d} W_t^v,
\end{array}\right.
$$
with no correlation between the Brownian motions $dW_t^x \cdot dW_t^v = 0$, as this breaks the affinity of the process when changing from measure $Q$ to the $T$-forward $Q^T$: 
$$
\left\{
\begin{array}{l}
    dx_t =  - \left( \frac{v}{\lambda} \left(1 - e^{-\lambda(T-t)} \right) + \lambda x_t \right) dt + \sqrt{v_t} \text{d}W_t^x,  \\
    dv_t =  \kappa (\theta - v_t)\text{d}t + \varepsilon \sqrt{v_t} \text{d} W_t^v,
\end{array}\right.
$$

The short rate itself:
$$ 
r_t = \alpha_t + x_t 
$$ 
where the HJM condition on $\alpha_t$ is described in the multiple-curve framework below.

Stochastic variance is an CIR process with non-central chi-squared distribution:
$$
\mathbb{P}\left(v_{t + \Delta}<v \mid v_{t}\right) \quad = \quad F_{\chi'^{2}}\left(\frac{4 \kappa v}{\varepsilon^{2}\left(1-e^{-\kappa \Delta}\right)} ; \frac{4 \kappa \theta}{\varepsilon^{2}}, \frac{4 v_{t} \kappa e^{-\kappa \Delta}}{\varepsilon^{2}\left(1-e^{-\kappa \Delta}\right)}\right) \quad
$$
over a time step $\Delta$, and admits an almost exact QE simulation scheme.  

Since no correlation leaks can occur, the Euler scheme is sufficient to evolve $x_t$ and $v_t$:
$$
x_{t+\Delta} \sim \mathcal{N} \left( x_t e^{-\lambda \Delta}, \quad \frac{v_t}{2 \lambda} \left( 1- e^{-2\lambda \Delta} \right) \right)
$$
and similarly in $T$-forward measure.

## 2. Multi-Curve models

### 2.1 Affine multi-curve models and IBOR rates

The short rate is given by:
$$
r_t = f(t) + \lambda^T \textbf{x}_t
$$
where $\textbf{x}_t$ is an affine process and $\lambda$ is constant. The latter drive also the instantaneous forward spread rates to other curves:
$$
s_t^{\delta} = s^{\delta}(t) + \gamma_{\delta}^T \textbf{x}_t
$$
enumerated by $\delta$, with $\gamma_{\delta}$ constant. If those spreads corresponds to IBOR rates, then $\delta$ are the tenors, and we require:
$$
0 \leq s_t^{\delta_i}  \leq s_t^{\delta_j}, \quad  \delta_i < \delta_j
$$
in which case we can calibrate to the available ZCB curves:
$$
T \rightarrow P_{t,T} = \mathbb{E}_t \left[ e^{- \int_{t,T} r_u du} \right], \quad P_t(T, \delta) = \mathbb{E}_t \left[ e^{ - \int_{t,T} \left(r_u + s^{\delta}_u \right)du} \right]
$$

where $P_{t,T}$ is the OIS curve, and the other correspond to IBOR forward rates at different tenors:
$$
L_t(T-\delta, T)=  \frac{P_t(T-\delta, \delta) - P_t(T, \delta)}{\delta \cdot P_t(T, \delta)}
$$

Denoting the forward spreads:
$$
S^{\delta}_t(T) = \frac{1 + \delta \cdot L_t(T-\delta, T)}{1 + \delta \cdot L^D_t(T-\delta,T)}
$$
where $L_t(T-\delta, T) =   \frac{P_{t,T-\delta} - P_{t,T}}{\delta P_{t,T-\delta} }$ is the forward looking RFR.

The HJM condition in that case reduces to:
$$
f(t) = - \frac{\partial}{\partial t} \log P_{0,t}  + \frac{\partial}{\partial t} \log \bar{P}_{0,t}, \quad s^{\delta}(t) = - \frac{\partial}{\partial t} \log S^\delta _0(t) + \frac{\partial}{\partial t} \log \bar{S}^\delta _0(t) 
$$
where the base curves $\bar{P}_{0,t}$ and $\bar{S}^\delta _0(t)$ are obtained from a model where $f(t)\equiv 0$ and $s^{\delta}(t) \equiv 0$.


IBOR quotes typically come from FRAs, whose present value at strike $K$ is given by:
$$
PV_t\left[K \right] = P_{t,T} S^{\delta}_t(T)- (1 + \delta K) P_{t, T+\delta}
$$

Using IRSs quotes, one solves for forward spreads $S^{\delta}_t(T)$ directly, as the former evaluates to:
$$
PV_t \left[\delta,  \delta', K\right] = \sum_{i \geq 1} \left( P_{t, T_{j-1}}  S^{\delta}_t(T_{j-1}) -  P_{t, T_{j}} \right) - \delta' K \sum_{j\geq 1} P_{t, T'_j}
$$
where $\delta = T_{i} - T_{i-1}$ is the floating leg tenor and $\delta' = T'_{j} - T'_{j-1}$ is the fixed leg tenor. 

A typical example can be obtained using self-exciting CIR processes for the forward spreads and Hull White dynamics for the rate:
$$
s_t^{\delta_j} = s^{\delta_j}(t) + \sum_{i \leq j} \gamma_i x_{t}^i, \quad \gamma_i \geq 0, \quad dx_{t}^i= \kappa_i (\theta_i - x_{t}^i) dt + \epsilon_i \sqrt{x_{t}^i} dW_t^i
$$
where tenors $\delta_{1} < \delta_{2} < \dots < \delta_{n}$ are in increasing order. 

The short rate  follows the Hull-White-Heston multi-factor model:
$$
r_t = f(t) + x_t^0, \quad dx_{t}^0 = - \lambda_0 x_{t}^0 dt + \sum_{i=1}^n \lambda_i \sqrt{x_{t}^i} dW_t^i
$$
where $\lambda_1^2 + \dots + \lambda_n^2 =1$, and all Brownian motions $W_t^i$ are independent.

### 2.2 Modelling Arithmetic-Average Compounding on a Key Rate

We are not confined to model IBOR rates with spreads $s_t^{\delta}$. In fact, we can choose any other curve, in which case we will need to fit whatever market quotes are available to us. 

In our case, we have a forward curve for arithmetic-average backward looking $A_{t,T}$ on a Key Rate, which is different from the OIS $r_t$ for which we also have forward curve. And we need to capture the smile of a volatility surface on $A_{t,T}$. 

We can add to the Hull-White-Heston model a stochastic spread between OIS short rate and the Key Rate:
$$
r_t = f(t) + x_t, \quad dx_{t} = - \lambda x_{t} dt + \sqrt{v_t} dW_t^x, \quad dv_t =  \kappa (\theta - v_t)dt + \varepsilon \sqrt{v_t} dW_t^v
$$
as above and the spread follows an CIR process near zero:
$$
s_t = s(t) + k_t, \quad dk_t =  - \gamma k_t dt + \xi dW_t^k
$$
with all Brownian motions $W_t^x, W_t^v$ and $W_t^k$ independent.

To fit the market data we need to match:
$$
A_{t,T} = \mathbb{E}^{Q^T}_{t} \left[ \frac{1}{\tau} \int_{T - \tau}^T r_u + s_u du \right] = \frac{ \mathbb{E}_{t}^{Q} \left[ \frac{1}{\tau} \int_{T - \tau}^T r_u + s_u du / B_T \right] }{\mathbb{E}_{t}^{Q} \left[ 1/B_T \right]}
$$
and the Caplet prices: 
$$
V^{\text{Caplet}}_t \left[ A_{t,T}, K \right] = B_t \mathbb{E}_{t}^{Q} \left[ \tau \left( \int_{T - \tau}^T r_u + s_udu - K \right)^+ / B_T\right] 
$$
all that keeping:
$$
f(t) = - \frac{\partial}{\partial t} \log P_{0,t}  + \frac{\partial}{\partial t} \log \bar{P}_{0,t}
$$
which does depend on the parameters driving $x_{t}$ and $v_t$ which are mainly influenced by the volatility surface.

### 2.3 Swaptions 

A physically-settled payer (+) or receiver (-) swaption at the start $T_0$ of the IRS swap expires with value:
$$
PV_{T_0} = \text{PVBP}(T_0) \left(\pm \left( S_{T_0} - K\right)\right)^+
$$
where the present value of basis point $\text{PVBP}(T_0) =  \delta' \sum_{i > 0} P_{T_0, T_i}$ is computed from the risk free OIS curve and the swap rate $S_{T_0}$ comes from the floating rate that might be backward looking or IBOR based.

Using $\text{PVBP}(t)$ as numeraire we can price the swaption:
$$
PV_t = \text{PVBP}(t) \cdot \mathbb{E}_{t}^{\text{PVBP}} \left[(\pm\left( S_{T_0} - K)\right)^+ \right] 
$$
in which the swap rate $S_t$ is naturally a martingale.

For cash-settled swaptions, the payoff is settled at $T_0$ according to the formula:
$$
PV_{T_0} = \text{Ann}(S_{T_0}) \left(\pm  \left( S_{T_0} - K\right) \right)^+, \quad \text{Ann}(s) =\sum_{i > 0} \frac{ \delta' }{(1 + \delta' s)^i }
$$

Market makers formula convention simply substitutes cash-annuity Ann for PVBP in the physically-settled case:
$$
PV_t = P_{t,T_0}  \text{Ann}(S_t) \cdot \mathbb{E}_{t}^{\text{PVBP}} \left[(\pm\left( S_{T_0} - K)\right)^+ \right], \quad S_t = \mathbb{E}_{t}^{\text{PVBP}} [S_{T_0}]
$$
which leads to a failure of put-call parity, especially when we are in IBOR multi-curve environment.

To account for the convexity correction needed, one introduces the cash-settled convexity adjusted PVBP:
$$
\text{CSCAP}(t) = B_t \cdot \mathbb{E}^Q_{t} \left[ \frac{\text{Ann}(T_0) }{B_{T_0}}  \right]
$$
and the cash-settled convexity adjusted forward:
$$
\text{CSCAF}(t) = \frac{B_t}{\text{CSCAP}(t)} \cdot \mathbb{E}^Q_{t} \left[ S_{T_0}\frac{\text{Ann}(T_0) }{B_{T_0}}  \right]
$$

In that case, we do obtain the desired put-call parity:
$$
PV_t\left[\text{payer}, K \right] - PV_t\left[\text{receiver}, K \right] = \text{CSCAP}(t) \cdot \left( \text{CSCAF}(t) - K \right)
$$